[package]
name = "scraping-example-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.9", features = ["json"] }
scraper = "0.21.0"
tokio = { version = "1.41.1", features = ["full"] }
